# 
# This file holds configuration properties
# for the Ferris TV AirDate Digest (TADD) application
#

# This is the resend.com API key
resendApiKey=re_abcabcabc

# This value is either "true" or "false"
# Configures if TADD sends the email or not
# TADD will only send the email if this property
# has the case insenstive value "true". Any
# other value, and TADD will not send the email.
sendEmail=true
