# 
# This file holds configuration properties
# for the Ferris TV AirDate Digest (TADD) application
#

# This is the resend.com API key
resendApiKey=re_abcabcabc

# This value is either "true" or "false"
# Configures if TADD sends the email or not
# TADD will only send the email if this property
# has the case insenstive value "true". Any
# other value, and TADD will not send the email.
sendEmail=true

# This value is either "true" or "false"
# Configures if the today's show information
# is included in the email or not. TRUE if this 
# property has the case insenstive value "true". 
# Any other value is FALSE.
showsForToday=true

# This value is an integer value.
# Cofigures the total number of days of show
# information to include in the email. This
# property works in combination with the 
# property "showsForToday"
#
# DEFAULT VALUE: 3
#
# If the value cannot be converted to a number,
# is less than or equal to zero, or is greater
# than 14, the DEFAULT VALUE will be used.
#
# EXAMPLE 1 
#   Let:
#     Today be MON and showsForToday=true and showsForDays=1
#   Then:
#     Email will contain show information for: MON
# 
# EXAMPLE 2
#   Let:
#     Today be MON and showsForToday=true and showsForDays=3
#   Then:
#     Email will contain show information for: MON, TUE, WED
# 
# EXAMPLE 3
#   Let:
#     Today be MON and showsForToday=false and showsForDays=1
#   Then:
#     Email will contain show information for: TUE
# 
# EXAMPLE 2
#   Let:
#     Today be MON and showsForToday=false and showsForDays=3
#   Then:
#     Email will contain show information for: TUE, WED, THU
# 
showsForDays=3
